### ISSUE TITLE
To Do List

### ISSUE THREAD

**Issue by MartGon** [MartGon/AWC#3]
# TODO

- [ ] Refactor AreaX classes to the ones described here: https://github.com/MartGon/AWC/issues/4
- [ ] Remove Script::UserData::UserData redundant namespace.
- [ ] Implement GetOptional template method in LuaTable and Utils, to be able to get a default value when a key/argument is not present.
- [ ] Change std::string paths to use std::filesystem::paths.
- [ ] Unit rotations, units can be facing to different directions (N, S, E, W). More info here: https://github.com/MartGon/AWC/issues/5
- [ ] LuaTable Check and CheckWrapper methods. They raise an error when key is not present.
- [ ] Tests clean up. Some test are implemented with some hacks or redundancy. Solve it.
- [ ] Check Copy/Move Constructors/Assignment in classes like Map, Game, etc.
- [ ] Replace AttackTable, DamageTable and CostTable with Table. Implement Default value in Table.
- [ ] Move everything in global namespace to AWC namespace in AWC lib.
- [ ] Excute script method should return a bool and/or string to describe an error that ocurred.
- [ ] Define which C classes are going to be passed as tables to the Lua environment. More info here: https://github.com/MartGon/AWC/issues/6
- [ ] Redesign Process history with turns in mind. More info here: https://github.com/MartGon/AWC/issues/7
- [ ] Unregister unit event handlers when it is removed from the Game. More info here https://github.com/MartGon/AWC/issues/8
- [ ] Allow customization of Event handlers invocation order
- [ ] Implement AttackArea and AttackReach. More info here: https://github.com/MartGon/AWC/issues/9
- [ ] WinCondition class. Holds a function to be evaluated every turn. Can also register to some events
- [ ] Redesign some of the already implemented classes around the operation system (Turn, Command, etc.)
- [ ] Add GetSubType member to UserData::Operation, so it can be retrieved from Lua to differentiate Script Operations.
- [ ] Allow to create Script operations by a function call instead of a file. Something like `game:CreateOperation(execute, undo)` or `game:CreateOperation({name = ..., execute = ..., undo = ...})`
- [ ] Unit Pathing cost based on team. Units could travel more easily through tiles where another unit is placed if they are on the same team.
- [ ] Dijkstra algorithm should take a Graph with unknown costs and return a Graph with the updated ones.
- [ ] Use std::bind for the event system to link the listening entity with its callback
- [ ] Refactor functions which take a smart pointer as input to take a & or * instead. ([https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#f7-for-general-use-take-t-or-t-arguments-rather-than-smart-pointers](url))

# Ideas
- [ ] Tile instances with extra cost. Depend on its state, the tile may have a different cost. Could be implemented as transforming the Tile to a different type as well
- [ ] Unit effects (think of Hearthstone unit effects: Battlecry, Rush, Deathrattle, etc.)
- [ ] Game::Load and Game::Start methods
- [ ] Composed processes, which hold more of them. They can go back to the queue after being executed, they leave once they are Done()
- [ ] Maps, Players, etc. can only be created from a Game instance. It increases coupling, but it becomes less error prone.
- [ ] Unit Graveryard. Save dead units in a table/list so they can be interacted with later.
- [ ] Game holds an array of Component which can be downcasted by type to extend its functionality
